[package]
name = "juno-driver-hue"
version = "1.4.0"
edition = "2024"
description = "Philips Hue bridges and the bulbs behind them"
publish = false

[lib]
name = "juno_driver_hue"
crate-type = ["cdylib", "rlib"]

[dependencies]
driver-sdk = { git = "https://github.com/junohouse/driver-sdk", branch = "main" }

[workspace]

[profile.release]
opt-level = "z"
codegen-units = 1
lto = true
strip = true
